<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#ML-First-lab" data-toc-modified-id="ML-First-lab-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>ML First lab</a></span></li></ul></div>

### ML First lab

*	Student ID:192050223
*	First Name:Liu
*	Last Name: Jun


In [2]:
import numpy as np

* Get your DingTalk number (write it manually to notebook) and split into sequence of three-digit numbers.  The tail with one two-digit number should be discarded. For example for ID=12345678900 this code should return sequence [123, 456, 789].  

In [3]:
def getSequence(x, step = 3):
    x = str(x)
    arr = []
    for i in range(0, len(x) - step + 1,step):
        arr.append(int(x[i:i + step]))
    return arr

In [4]:
ID = 18190948520
sequence = getSequence(ID)
print(sequence)

[181, 909, 485]


* Convert this sequence of numbers into 3x3 numpy matrix A where each element of previous array is a row and one digit of each number is a column. For example, for this sequence [123, 456, 789] the matrix will be equal to [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
mat = [getSequence(seq,1) for seq in sequence]
print(mat)

[[1, 8, 1], [9, 0, 9], [4, 8, 5]]


* Read the NumPy documentation and compute the reversed matrix A (if you can reverse it), transposed matrix A, multiplication of matrix A and matrix A^(-1) or matrix A and transposed A, create a submatrix consists of the first and third rows of matrix A

In [9]:
matrix = np.array(mat)

transposed = matrix.T
inv = np.linalg.inv(matrix)
inv = np.matrix(mat).I

ans1 = matrix * transposed
ans2 = matrix * inv

sub_matrix=matrix[[0,2]] 

print("transosed==============:)=========")
print(transposed)
print("inv==============:)===============")
print(inv)
print("asn1==============:)==============")
print(ans1)
print("ans2==============:)==============")
print(ans2)
print("sum_matrix==============:)========")
print(sub_matrix)

transosed==============:)=========
[[1 9 4]
 [8 0 8]
 [1 9 5]]
inv==============:)===============
[[ 1.00000000e+00  4.44444444e-01 -1.00000000e+00]
 [ 1.25000000e-01 -1.38888889e-02 -6.93889390e-18]
 [-1.00000000e+00 -3.33333333e-01  1.00000000e+00]]
asn1==============:)==============
[[ 1 72  4]
 [72  0 72]
 [ 4 72 25]]
ans2==============:)==============
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 2.22044605e-16  1.00000000e+00 -2.22044605e-16]
 [ 2.22044605e-16  0.00000000e+00  1.00000000e+00]]
sum_matrix==============:)========
[[1 8 1]
 [4 8 5]]
